### ISSUE TITLE
Serial Monitor gives garbage Data

### ISSUE THREAD

**Issue by Chris-The-Tuner** [lasitha-sparrow/Makeskyblue_wifi_Controller#3]
Hi there,
i tried your newest Release (ESP8266).
Sadly on the Serial Monitor i get nothing except for not-usable Data.
Blynk shows my Device as online but i cant get Data at all as it seems.

Do you maybe have an Idea what to check here ?

Greetings Chris

**Comment by Chris-The-Tuner** [comment]
Well i just seen one error myself, did reverse the TX/RX lines and Blynk shows Data.
Sadly the Serial Monitor still soes not output anything useful, but thats not a huge Problem so...

Sorry for asking, my bad ...

**Comment by lasitha-sparrow** [comment]
Hey,

So, since we're utilizing hardware RX and TX lines in the ESP8266, we won't see the values on the serial monitor. That's because it also relies on the hardware serial.
Here's a workaround: try using a software serial connection on the Makeskyblue controller instead, and keep the hardware serial pins untouched. This way, you can still use them on the serial monitor.
I opted for hardware serial initially because it provides a more reliable connection between the solar MSB and ESP.
Hope that clarifies things!
